#!/bin/sh
# Emit litestream config to stdout (written to $USERS_ROOT/litestream.yml):
# one db entry per user, replicated to MinIO bucket `assistant` under
# users/<name>/appspace-db. Secrets stay in the environment.
set -eu
cd "$(dirname "$0")/.."
. scripts/lib-users.sh

cat <<'EOF'
# GENERATED by scripts/render-litestream.sh — do not edit. Regenerated on
# every user-add/remove; restart via scripts/restart-litestream.sh.
dbs:
EOF
for u in $(users_list); do
  cat <<EOF
  - path: $USERS_ROOT/$u/appspace/appspace.db
    replicas:
      - type: s3
        bucket: assistant
        path: users/$u/appspace-db
        endpoint: http://127.0.0.1:9000
        access-key-id: \${LITESTREAM_ACCESS_KEY_ID}
        secret-access-key: \${LITESTREAM_SECRET_ACCESS_KEY}
        force-path-style: true
        retention: 168h # 7 days of point-in-time restore
EOF
done
